/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhySynergyStoriesRouteImport } from './routes/why-synergy.stories'
import { Route as WhySynergyBusinessImpactRouteImport } from './routes/why-synergy.business-impact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySynergyStoriesRoute = WhySynergyStoriesRouteImport.update({
  id: '/why-synergy/stories',
  path: '/why-synergy/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySynergyBusinessImpactRoute =
  WhySynergyBusinessImpactRouteImport.update({
    id: '/why-synergy/business-impact',
    path: '/why-synergy/business-impact',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/why-synergy/business-impact' | '/why-synergy/stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/why-synergy/business-impact' | '/why-synergy/stories'
  id: '__root__' | '/' | '/why-synergy/business-impact' | '/why-synergy/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhySynergyBusinessImpactRoute: typeof WhySynergyBusinessImpactRoute
  WhySynergyStoriesRoute: typeof WhySynergyStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-synergy/stories': {
      id: '/why-synergy/stories'
      path: '/why-synergy/stories'
      fullPath: '/why-synergy/stories'
      preLoaderRoute: typeof WhySynergyStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-synergy/business-impact': {
      id: '/why-synergy/business-impact'
      path: '/why-synergy/business-impact'
      fullPath: '/why-synergy/business-impact'
      preLoaderRoute: typeof WhySynergyBusinessImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhySynergyBusinessImpactRoute: WhySynergyBusinessImpactRoute,
  WhySynergyStoriesRoute: WhySynergyStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
