/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhySynergyRouteImport } from './routes/why-synergy'
import { Route as FakehunterRouteImport } from './routes/fakehunter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhySynergyTechnologyRouteImport } from './routes/why-synergy.technology'
import { Route as WhySynergyStoriesRouteImport } from './routes/why-synergy.stories'
import { Route as WhySynergyBusinessImpactRouteImport } from './routes/why-synergy.business-impact'

const WhySynergyRoute = WhySynergyRouteImport.update({
  id: '/why-synergy',
  path: '/why-synergy',
  getParentRoute: () => rootRouteImport,
} as any)
const FakehunterRoute = FakehunterRouteImport.update({
  id: '/fakehunter',
  path: '/fakehunter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySynergyTechnologyRoute = WhySynergyTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => WhySynergyRoute,
} as any)
const WhySynergyStoriesRoute = WhySynergyStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => WhySynergyRoute,
} as any)
const WhySynergyBusinessImpactRoute =
  WhySynergyBusinessImpactRouteImport.update({
    id: '/business-impact',
    path: '/business-impact',
    getParentRoute: () => WhySynergyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fakehunter': typeof FakehunterRoute
  '/why-synergy': typeof WhySynergyRouteWithChildren
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
  '/why-synergy/technology': typeof WhySynergyTechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fakehunter': typeof FakehunterRoute
  '/why-synergy': typeof WhySynergyRouteWithChildren
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
  '/why-synergy/technology': typeof WhySynergyTechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fakehunter': typeof FakehunterRoute
  '/why-synergy': typeof WhySynergyRouteWithChildren
  '/why-synergy/business-impact': typeof WhySynergyBusinessImpactRoute
  '/why-synergy/stories': typeof WhySynergyStoriesRoute
  '/why-synergy/technology': typeof WhySynergyTechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fakehunter'
    | '/why-synergy'
    | '/why-synergy/business-impact'
    | '/why-synergy/stories'
    | '/why-synergy/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fakehunter'
    | '/why-synergy'
    | '/why-synergy/business-impact'
    | '/why-synergy/stories'
    | '/why-synergy/technology'
  id:
    | '__root__'
    | '/'
    | '/fakehunter'
    | '/why-synergy'
    | '/why-synergy/business-impact'
    | '/why-synergy/stories'
    | '/why-synergy/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FakehunterRoute: typeof FakehunterRoute
  WhySynergyRoute: typeof WhySynergyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-synergy': {
      id: '/why-synergy'
      path: '/why-synergy'
      fullPath: '/why-synergy'
      preLoaderRoute: typeof WhySynergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakehunter': {
      id: '/fakehunter'
      path: '/fakehunter'
      fullPath: '/fakehunter'
      preLoaderRoute: typeof FakehunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-synergy/technology': {
      id: '/why-synergy/technology'
      path: '/technology'
      fullPath: '/why-synergy/technology'
      preLoaderRoute: typeof WhySynergyTechnologyRouteImport
      parentRoute: typeof WhySynergyRoute
    }
    '/why-synergy/stories': {
      id: '/why-synergy/stories'
      path: '/stories'
      fullPath: '/why-synergy/stories'
      preLoaderRoute: typeof WhySynergyStoriesRouteImport
      parentRoute: typeof WhySynergyRoute
    }
    '/why-synergy/business-impact': {
      id: '/why-synergy/business-impact'
      path: '/business-impact'
      fullPath: '/why-synergy/business-impact'
      preLoaderRoute: typeof WhySynergyBusinessImpactRouteImport
      parentRoute: typeof WhySynergyRoute
    }
  }
}

interface WhySynergyRouteChildren {
  WhySynergyBusinessImpactRoute: typeof WhySynergyBusinessImpactRoute
  WhySynergyStoriesRoute: typeof WhySynergyStoriesRoute
  WhySynergyTechnologyRoute: typeof WhySynergyTechnologyRoute
}

const WhySynergyRouteChildren: WhySynergyRouteChildren = {
  WhySynergyBusinessImpactRoute: WhySynergyBusinessImpactRoute,
  WhySynergyStoriesRoute: WhySynergyStoriesRoute,
  WhySynergyTechnologyRoute: WhySynergyTechnologyRoute,
}

const WhySynergyRouteWithChildren = WhySynergyRoute._addFileChildren(
  WhySynergyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FakehunterRoute: FakehunterRoute,
  WhySynergyRoute: WhySynergyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
